### ISSUE TITLE
Make energy costs of builtin cards more fair and balanced

### ISSUE THREAD

**Issue by AlexNisnevich** [wordbots/wordbots-core#230]

**Comment by Dbz** [comment]
We should make the importer. Then you can start with removing all of the old cards from production/staging (or migrating them to the test database because they're used in testing, right?), and import everything from the core-set spreadsheet.

**Comment by AlexNisnevich** [comment]
I think I'm fine doing it by hand for now, but an importer would be good to have by v1.0.
