### ISSUE TITLE
Better card in hand UX in game

### ISSUE THREAD

**Issue by Dbz** [wordbots/wordbots-core#254]
Currently the cards are overlapping, so when you hover over part of a card, you get to see the whole card. This makes it easy to see the cards to the left of the card you are hovering over, but it becomes difficult to view cards to the right of the care you are hovering over. You need to be able to hover over any card at any time regardless of what card is currently being displayed.

**Comment by AlexNisnevich** [comment]
Closing because this is probably no longer an issue now that there's a max hand size.
