### ISSUE TITLE
Visual Difference Between Robots and Structures when playing

### ISSUE THREAD

**Issue by Dbz** [wordbots/wordbots-core#283]
Robots and structures should be visually different on the game board. For example, structures have a different tile background color.

**Comment by Dbz** [comment]
I'm not sure just graying out the "robot" image is enough to differentiate the card from a robot. I'll keep thinking about this.

**Comment by AlexNisnevich** [comment]
Fair point. I'll reopen the issue.

**Comment by Dbz** [comment]
Until we figure something more permanent out, structures should also be grayed out on the game board. They shouldn't be a specific color. This should give them visual distinction
