### ISSUE TITLE
Dictionary missing key terms

### ISSUE THREAD

**Issue by Dbz** [wordbots/wordbots-core#308]
The dictionary is missing important terms like `Defender`

**Comment by AlexNisnevich** [comment]
Keywords are found in the keywords tab of the dictionary.

**Comment by Dbz** [comment]
I didn't realize those were tabs!

**Comment by AlexNisnevich** [comment]
Oops! UI work may be needed ...

**Comment by Dbz** [comment]
I'll make a ticket
