### ISSUE TITLE
Better tabs UI in dictionary

### ISSUE THREAD

**Issue by Dbz** [wordbots/wordbots-core#310]
It is a little unclear that the tabs in the dictionary are tabs. A divider or "tab" look would be very helpful. 

![](https://www.typesettercms.com/data/_addondata/x_Addons/screenshots/7/307/tabs-c02ca91c.jpg)

**Comment by Dbz** [comment]
I would recommend re-opening this. The tabs are still not as clear as they could be. If I didn't know they were there, I still might miss them.

**Comment by AlexNisnevich** [comment]
Unfortunately, I'm not sure how much better we can do. This is [how tabs work in Material UI](http://www.material-ui.com/#/components/tabs).

(See also [Google's material design guidelines for tabs](https://material.io/guidelines/components/tabs.html).

**Comment by Dbz** [comment]
So there are a couple things we can do. Right now the indicator is white underneath the tab. That makes it almost invisible- so it could be red. The active tab could also be a different color.

**Comment by AlexNisnevich** [comment]
Good point. Would you like to try making the colors clearer? I think that should be pretty easy to tweak.

**Comment by AlexNisnevich** [comment]
How about this?
<img width="1371" alt="screen shot 2017-06-05 at 3 50 15 pm" src="https://cloud.githubusercontent.com/assets/415965/26806635/cf00e110-4a06-11e7-9203-d6a6069d4c4c.png">

**Comment by Dbz** [comment]
That's perfect
