### ISSUE TITLE
[minor] In tutorial, a hover tooltip is centered off screen when left menu is hidden

### ISSUE THREAD

**Issue by timhwang21** [wordbots/wordbots-core#336]
![screenshot 2017-06-03 18 03 25](https://cloud.githubusercontent.com/assets/5831434/26757362/336c1fce-4887-11e7-8a06-93ef79110c56.png)

When the hamburger menu is clicked, the tooltip properly orients itself.

**Comment by AlexNisnevich** [comment]
Best solution would probably be to always keep the left menu open in tutorial mode.
