### ISSUE TITLE
Move timer and end turn button to the right side

### ISSUE THREAD

**Issue by Dbz** [wordbots/wordbots-core#393]
Move the timer and and turn button to the right side and remove that left side menu. Then all of the game info will be on the right hand side, and with the room cleaned up from the left side, the game board can be a little bit bigger.

**Comment by AlexNisnevich** [comment]
Wouldn't putting them on the right side take up as much space as on the left side? Could you mock up roughly how you think it should look?

**Comment by Dbz** [comment]
Yes, I can do this 👍

**Comment by jacobnisnevich** [comment]
I think he means something like this?

![image](https://user-images.githubusercontent.com/1996162/27997211-1cea4a04-64a8-11e7-9863-6cb08bf16676.png)

**Comment by Dbz** [comment]
That's exactly what I mean. I think this will let us make the board a little bigger too now that it is all on the right side and there is no left-side-menu-bar

**Comment by jacobnisnevich** [comment]
Yeah and at the very least there's more room for cards this way.

**Comment by AlexNisnevich** [comment]
Interesting. @jacobnisnevich How hard do you think it would be to move all of the GameMenu to a new area underneath the chat? This also has the side effect of making #377 unnecessary since we won't need to collapse the game menu anymore!

**Comment by jacobnisnevich** [comment]
Probably not too hard actually. Is the order fine as is? Chat above menu?

**Comment by AlexNisnevich** [comment]
@Dbz What do you think? The menu should probably also be a bit smaller (though it should be able to accomodate

**Comment by Dbz** [comment]
I think it looks pretty good like this actually. Your comment inspires cards that give you "powers" under that menu. Like `Activate (5) : Deal 1 damage to a robot`. Or  `Activate (5) : Spawn a 3/3/1 Bot`. Just thoughts.

I'm also weary about chat. Trolling is huge in these sorts of online games. However, that is a problem to deal with when it pops up.

**Comment by AlexNisnevich** [comment]
The above is already how activated abilities work – they're activated in the game menu.

**Comment by Dbz** [comment]
Oh, I haven't played with Activated abilities yet 🐙
