### ISSUE TITLE
Test End of turn effects don't correctly trigger a player win

### ISSUE THREAD

**Issue by john-patterson** [wordbots/wordbots-core#571]
Given an enemy kernel with health K. If a player has a card with an effect like "deal M damage to the opponent at the end of your turn" where M >= K, I would expect this to result in a win for the player. Instead the enemy is given one more turn, and it is at the end of the player's next turn that the win is decided. 

There's another interesting edge case to consider wherein both players have cards to this effect and a sufficient amount of health to die in one turn. Player A will defeat the kernel of player B at the end of their turn, and then player B will defeat the kernel of player A at the end of player B's turn. Presumably this would result in a win for player A.

This is fixed by https://github.com/wordbots/wordbots-core/pull/647, but still needs an investigation and a test.

**Comment by AlexNisnevich** [comment]
Hey, this is something you could fix, @john-patterson ! 😉 

Check out the `endTurn()` function in [`util/game.js`](https://github.com/wordbots/wordbots-core/blob/master/src/common/util/game.js). It looks like it just needs a `checkVictoryConditions` call. 

Might also be nice to have a test for this (in [`test/reducers/game.spec.js`](https://github.com/wordbots/wordbots-core/blob/master/test/reducers/game.spec.js)).

**Comment by AlexNisnevich** [comment]
Alternatively, maybe the `triggerEvent` method should have a `checkVictoryConditions` call at the end?
