### ISSUE TITLE
"when your opponent plays a structure or robot" effect disallows playing cards

### ISSUE THREAD

**Issue by MichaelEbert** [wordbots/wordbots-core#597]
the effect
"when your opponent plays a structure or a robot, gain 1 life."
parses, but in game prohibits opponent from playing any cards (robots, structures, or events).

**Comment by AlexNisnevich** [comment]
Can you check to see if there is any error in the JavaScript console?

**Comment by MichaelEbert** [comment]
Yep.
TypeError: e.toLowerCase is not a function
Stack trace:
t.stringToType@http://app.wordbots.io/static/bundle.js:1:82380
condition@http://app.wordbots.io/static/bundle.js:1:419111
o@http://app.wordbots.io/static/bundle.js:1:118018
i@http://app.wordbots.io/static/bundle.js:1:118319
triggerEvent/a</<@http://app.wordbots.io/static/bundle.js:1:118634
triggerEvent/a<@http://app.wordbots.io/static/bundle.js:1:118458
Zt@http://app.wordbots.io/static/bundle.js:1:10459
Qa@http://app.wordbots.io/static/bundle.js:1:45203
e/hr.flatMap@http://app.wordbots.io/static/bundle.js:1:55627
triggerEvent@http://app.wordbots.io/static/bundle.js:1:118384
e@http://app.wordbots.io/static/bundle.js:1:419035
y@http://app.wordbots.io/static/bundle.js:1:421256
h@http://app.wordbots.io/static/bundle.js:1:420306
u/<@http://app.wordbots.io/static/bundle.js:1:272523
v@http://app.wordbots.io/static/bundle.js:1:270428
v/</</<@http://app.wordbots.io/static/bundle.js:1:878804
t.default/</</</<@http://app.wordbots.io/static/bundle.js:1:904121
t.default/</</<@http://app.wordbots.io/static/bundle.js:1:903944
t.default/</<@http://app.wordbots.io/static/bundle.js:1:905280
t.default/</<@http://app.wordbots.io/static/bundle.js:1:904628
r/</</<@http://app.wordbots.io/static/bundle.js:1:905007
onPlaceRobot@http://app.wordbots.io/static/bundle.js:1:437508
t/o.placePiece@http://app.wordbots.io/static/bundle.js:1:439786
t/o.onSelectTile@http://app.wordbots.io/static/bundle.js:1:440074
t/r.onHexClick@http://app.wordbots.io/static/bundle.js:1:1113042
t/r.handleClickHex@http://app.wordbots.io/static/bundle.js:1:1090939
D@http://app.wordbots.io/static/bundle.js:1:2101795
invokeGuardedCallback@http://app.wordbots.io/static/bundle.js:1:2101074
invokeGuardedCallbackAndCatchFirstError@http://app.wordbots.io/static/bundle.js:1:2101167
Q@http://app.wordbots.io/static/bundle.js:1:2102842
ee@http://app.wordbots.io/static/bundle.js:1:2103299
ne@http://app.wordbots.io/static/bundle.js:1:2103484
J@http://app.wordbots.io/static/bundle.js:1:2103111
se@http://app.wordbots.io/static/bundle.js:1:2104218
Xt@http://app.wordbots.io/static/bundle.js:1:2127604
Kt@http://app.wordbots.io/static/bundle.js:1:2118247
batchedUpdates@http://app.wordbots.io/static/bundle.js:1:2161574
lt@http://app.wordbots.io/static/bundle.js:1:2112389
Zt@http://app.wordbots.io/static/bundle.js:1:2118716
