### ISSUE TITLE
Allow draws as a possible endgame state (if, e.g. both kernels get destroyed simultaneously)

### ISSUE THREAD

**Issue by AlexNisnevich** [wordbots/wordbots-core#655]

**Comment by wuweiweiwu** [comment]
In what scenario is it possible for both kernels to get destroyed simultaneously? Like where you play a card that damages both kernels?

**Comment by AlexNisnevich** [comment]
Yeah, or if some ability takes effect (triggered, activated, or passive)
that reduces the health of both kernels simultaneously.
